#!/usr/bin/env bash

ROOT=$(
    cd $(dirname "$0")
    pwd
)

PREFIX="${ROOT}/src/build"
SE2="${ROOT}/tools/se2"
IGRAPH="${SE2}/vendor/igraph"

[ -f "${SE2}/SE2_VERSION" ] && rm "${SE2}/SE2_VERSION"
[ -f "${IGRAPH}/IGRAPH_VERSION" ] && rm "${IGRAPH}/IGRAPH_VERSION"

[ -d "${PREFIX}" ] && rm -rf "${PREFIX}"
[ -d "${ROOT}/build" ] && rm -rf "${ROOT}/build"
