#!/usr/bin/env sh

ROOT=$(
    cd "$(dirname "$0")" || exit
    pwd
)

[ -f "${ROOT}/src/Makevars" ] && rm "${ROOT}/src/Makevars"
rm "${ROOT}/src/include/config.h"
rm "${ROOT}"/config.*
find "${ROOT}/src" -name '*.o' -not -path "*/tests/*" -exec rm {} \;
