# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R-CMD-check

on:
  - workflow_call

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }}-${{ matrix.config.arpack }}-arpack)

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest, r: 'release', arpack: internal}
          - {os: macos-latest, r: 'release', arpack: external}
          - {os: windows-latest, r: 'release', arpack: internal}
          - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release', arpack: external}
          - {os: ubuntu-latest, r: 'release', arpack: internal}
          - {os: ubuntu-latest, r: 'release', arpack: external}
          - {os: ubuntu-latest, r: 'oldrel-1', arpack: external}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: always
          extra-packages: any::rcmdcheck any::igraph any::scRNAseq any::SummarizedExperiment
          needs: check

      - name: Install arpack on macOS
        if: ${{ runner.os == 'macOS' && matrix.config.arpack == 'external' }}
        run: brew install arpack

      - name: Install Windows system dependencies
        if: runner.os == 'Windows'
        shell: bash
        run: |
          pacman -S mingw-w64-x86_64-toolchain --noconfirm
          pacman -S mingw-w64-x86_64-make --noconfirm
          pacman -S mingw-w64-x86_64-arpack --noconfirm

      - name: Install Linux system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install gcc

      - name: Install arpack for linux
        if: ${{ runner.os == 'Linux' && matrix.config.arpack == 'external' }}
        run: sudo apt install libarpack2-dev

      - name: Clone igraph
        shell: bash
        run: |
          cd src/se2
          git submodule init
          git submodule update --recursive

      # Seems like the line-endings get changed to CRLF when checking out from
      # git repo? R CMD check keeps complaining that configure.ac doesn't have
      # LF line endings on Windows build.
      - name: Fix line-endings
        if: runner.os == 'Windows'
        run: |
          dos2unix configure.ac
          dos2unix src/include/config.h.win

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

      - name: Upload build
        if: ${{ github.ref_type == 'tag' && runner.os == 'Linux' && matrix.config.r == 'release' && matrix.config.arpack == 'external'}}
        uses: actions/upload-artifact@v4
        with:
          name: speakeasyR-${{ github.sha }}
          path: check/speakeasyR_*.tar.gz
